#!/bin/sh
# Ordinary text mode preserves govulncheck's finding/error exit status.
# JSON/SARIF/VEX output can exit successfully with vulnerabilities.
set -eu
cd "$(dirname "$0")/.."
govulncheck -format text -show verbose -test ./...
govulncheck -format text -show verbose -test -tags integration ./...
# Reject vulnerable imported packages even if no affected symbol is called.
# Verbose output retains unused-module advisories for documented disposition.
govulncheck -format text -show verbose -scan package -test ./...
govulncheck -format text -show verbose -scan package -test -tags integration ./...
