#!/usr/bin/env bash
# Sourced only by trusted root startup/operator scripts; never print secrets.
set +x
set -Eeuo pipefail
DATA=/var/lib/roisey-else
CONTROL=$DATA/.control
PGDATA=$DATA/18/docker
SOCKET=/run/roisey-else/postgres
export PGDATA

log() { printf '[%s] %s\n' "$1" "$2" >&2; }
fail() { log init "$1"; exit 1; }
require_root() { [[ $EUID == 0 ]] || fail operator_requires_root; }
load_credentials() {
  local file=$CONTROL/database.credentials
  [[ -f $file && ! -L $file && $(stat -c '%u:%a:%h' "$file") == 0:600:1 ]] || fail private_database_credentials_unavailable
  mapfile -t task_passwords < "$file"
  [[ ${#task_passwords[@]} == 2 && ${task_passwords[0]} =~ ^[0-9a-f]{64}$ && ${task_passwords[1]} =~ ^[0-9a-f]{64}$ ]] || fail private_database_credentials_invalid
  MIGRATOR_SECRET=${task_passwords[0]}
  RUNTIME_SECRET=${task_passwords[1]}
  unset task_passwords
}
clean_database_environment() {
  unset POSTGRES_PASSWORD MIGRATOR_PASSWORD RUNTIME_PASSWORD DATABASE_URL MIGRATION_DATABASE_URL BOOTSTRAP_DATABASE_URL
  unset PGPASSWORD PGPASSFILE PGSERVICE PGSERVICEFILE PGHOST PGPORT PGDATABASE PGUSER PGOPTIONS
}
owner_psql() {
  PGHOST=$SOCKET PGCONNECT_TIMEOUT=2 PGOPTIONS='-c statement_timeout=30000 -c lock_timeout=5000' \
    exec gosu postgres psql -X --username postgres --dbname else --set ON_ERROR_STOP=1 "$@" 9>&-
}
